default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: wastrel_development
test:
  <<: *default
  database: wastrel_test

production:
  <<: *default
  database: wastrel_production
  username: wastrel
  password: <%= ENV['WASTREL_DATABASE_PASSWORD'] %>
